[profile.default]
src = 'contracts'
test = 'test'
script = 'foundry-script'
out = 'out'
fs_permissions = [{ access = "read-write", path = "./out" }]
libs = ['lib', 'node_modules']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]
cache = true
cache_path = 'cache'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
evm_version = "paris"
verbosity = 3
ignored_error_codes = [1878, 5574]
ffi = true
initial_balance = '0xffffffffffffffffffffffff'
bytecode_hash = 'none'

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[fuzz]
runs = 512

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
multiline_func_header = 'params_first'

[rpc_endpoints]
bsc = "${RPC_BSC}" # set by .env
local = "http://127.0.0.1:8545"

# OTS-only profile for faster development
[profile.ots]
src = 'contracts/ots'
test = 'test/ots'
out = 'out'
libs = ['lib', 'node_modules']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]
optimizer = true
optimizer_runs = 200
evm_version = "paris"
verbosity = 3
